name: Python_Script.py
on:
  schedule:
    - cron: '* * * * *' 
 
workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
       - uses: actions/checkout@v2 # checkout the repository content
       - uses: actions/setup-python@v2
         with:
             python-version: 3.x
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: execute py script 
        env:
            Api_key: ${{ secrets.API_KEY }}
            Email: ${{ secrets.EMAIL }}   
        run: python Python_Script.py

    


